Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2024
Var
numero : inteiro
numero1,numero2 : inteiro

Inicio
escreval ("digite o primeiro numero")
leia (numero1)
escreval ("digite o segundo numero")
leia (numero2)
 se numero1 = numero2 entao

 


Fimalgoritmo