Algoritmo "exercicio 3"

Var
primeiroNumero, segundoNumero : inteiro


Inicio
// precisa pegar dois numeros
escreval("Digite primeiro numero: ")
leia  (primeiroNumero)
escreval ("Digite o segundo numero: ")
leia(segundoNumero)

//mostrar mensagem comparando numeros
se(primeiroNumero = segundoNumero) entao
escreval ("Numeros Iguais")
senao
se(primeiroNumero > segubdoNumero) entao
escreval ("Primeiro numero maior!")
senao
ecreval(" Segundo numero maior!")
fimSe
fimSe


Fimalgoritmo