Algoritmo "semnome"

Var
valorTotal: real

procedimento mostrarMensagem ()
Inicio
valorTotal <- valorTotal + valor
escreval ("Bom Tarde!")
fimProcedimento

 procedimento acrescentarValor (valor : real)
 var
msg <- caractere
inicio
msg <- "uma mensagem legal"
valorTotal <- valorTotal + valor
escreva (msg)
fimProcedimento

Inicio
mostrarMensagem ()

acrescentarValor(50)
acrescentarValor(1.99)
acrescentarValor(2)
acrescentarValor(2000)

escreval ( valorTotal)

Fimalgoritmo